FROM openjdk:11-jdk-stretch
VOLUME /tmp
ADD labdaybackendspring-0.0.1-SNAPSHOT.jar labdaybackendspring-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","labdaybackendspring-0.0.1-SNAPSHOT.jar"]
