version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8080"
  admin:
    build:
      context: ./frontend
      dockerfile: Dockerfile.admin
    ports:
      - "${FRONTEND_PORT}:3000"
  db:
    image: postgres:11-alpine
    command: -c "track_commit_timestamp=on"
    env_file: .env
