export const restConstants = {
    POST_PLACE_REQUEST: 'POST_PLACE_REQUEST',
    GET_PLACE_REQUEST: 'GET_PLACE_REQUEST',

    POST_PATH_REQUEST: 'POST_PATH_REQUEST',
    GET_PATH_REQUEST: 'GET_PATH_REQUEST'
}