export const restConstants = {
    POST_PLACE_REQUEST: 'POST_PLACE_REQUEST',
    GET_PLACE_REQUEST: 'GET_PLACE_REQUEST',
    DELETE_PLACE_REQUEST: 'DELETE_PLACE_REQUEST',
    POST_SPEAKER_REQUEST: 'POST_SPEAKER_REQUEST',
    GET_SPEAKER_REQUEST: 'GET_SPEAKER_REQUEST',
    DELETE_SPEAKER_REQUEST: 'DELETE_SPEAKER_REQUEST',
}