export const restConstants = {
    POST_PLACE_REQUEST: 'POST_PLACE_REQUEST',
    GET_PLACE_REQUEST: 'GET_PLACE_REQUEST',

    POST_PATH_REQUEST: 'POST_PATH_REQUEST',
    GET_PATH_REQUEST: 'GET_PATH_REQUEST',

    POST_EVENT_REQUEST: 'POST_EVENT_REQUEST',
    GET_EVENT_REQUEST: 'GET_EVENT_REQUEST',
    DELETE_EVENT_REQUEST: 'DELETE_EVENT_REQUEST',

    POST_TIMETABLE_REQUEST: 'POST_TIMETABLE_REQUEST',
    GET_TIMETABLE_REQUEST: 'GET_TIMETABLE_REQUEST',
    DELETE_TIMETABLE_REQUEST: 'DELETE_TIMETABLE_REQUEST',
}